[2023-11-29 14:49:35,066] {processor.py:163} INFO - Started process (PID=14629) to work on /opt/airflow/dags/our_first_dag.py
[2023-11-29 14:49:35,066] {processor.py:642} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-11-29 14:49:35,067] {logging_mixin.py:109} INFO - [2023-11-29 14:49:35,067] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-11-29 14:49:35,070] {logging_mixin.py:109} INFO - [2023-11-29 14:49:35,069] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay' : timedelta(minutes=2)
NameError: name 'timedelta' is not defined
[2023-11-29 14:49:35,080] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-11-29 14:49:35,087] {processor.py:171} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.023 seconds
[2023-11-29 19:01:05,955] {processor.py:163} INFO - Started process (PID=14821) to work on /opt/airflow/dags/our_first_dag.py
[2023-11-29 19:01:05,982] {processor.py:642} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2023-11-29 19:01:05,983] {logging_mixin.py:109} INFO - [2023-11-29 19:01:05,983] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2023-11-29 19:01:05,988] {logging_mixin.py:109} INFO - [2023-11-29 19:01:05,987] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 8, in <module>
    'retry_delay' : timedelta(minutes=2)
NameError: name 'timedelta' is not defined
[2023-11-29 19:01:06,046] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2023-11-29 19:01:06,094] {processor.py:171} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.142 seconds
